-- migrate:up

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE product_categories (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug        text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name        text NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 100),
    description text NOT NULL DEFAULT '',
    sort_order  int NOT NULL DEFAULT 0,
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id       uuid REFERENCES product_categories(id) ON DELETE SET NULL,
    sku               text NOT NULL UNIQUE,
    slug              text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name              text NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 160),
    description       text NOT NULL DEFAULT '',
    short_description text NOT NULL DEFAULT '',
    price             int NOT NULL CHECK (price > 0),
    qty               int NOT NULL DEFAULT 0 CHECK (qty >= 0),
    min_qty           int NOT NULL DEFAULT 0 CHECK (min_qty >= 0),
    image_url         text,
    gallery           jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(gallery) = 'array'),
    featured          boolean NOT NULL DEFAULT false,
    sort_order        int NOT NULL DEFAULT 0,
    active            boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX products_listing_idx
    ON products (active, category_id, featured DESC, sort_order, name);
CREATE INDEX products_search_idx
    ON products USING gin (to_tsvector('simple', name || ' ' || description || ' ' || sku));

CREATE TABLE shopping_carts (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    token_hash     bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    customer_email text,
    status         text NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active', 'converted', 'abandoned', 'expired')),
    currency       char(3) NOT NULL,
    expires_at     timestamptz NOT NULL DEFAULT now() + interval '30 days',
    last_activity  timestamptz NOT NULL DEFAULT now(),
    converted_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX shopping_carts_recovery_idx
    ON shopping_carts (status, last_activity) WHERE status = 'active';

CREATE TABLE shopping_cart_items (
    cart_id    uuid NOT NULL REFERENCES shopping_carts(id) ON DELETE CASCADE,
    product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity   int NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (cart_id, product_id)
);

CREATE TABLE shop_orders (
    id                           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number                 bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    cart_id                      uuid UNIQUE REFERENCES shopping_carts(id) ON DELETE SET NULL,
    idempotency_hash             bytea NOT NULL UNIQUE CHECK (octet_length(idempotency_hash) = 32),
    customer_name                text NOT NULL CHECK (length(trim(customer_name)) BETWEEN 2 AND 120),
    customer_email               text NOT NULL,
    customer_phone               text NOT NULL,
    status                       text NOT NULL
                                 CHECK (status IN ('pending', 'confirmed', 'ready', 'completed', 'cancelled')),
    payment_method               text NOT NULL
                                 CHECK (payment_method IN ('pay_at_store', 'mercado_pago')),
    payment_status               text NOT NULL DEFAULT 'unpaid'
                                 CHECK (payment_status IN ('unpaid', 'pending', 'approved', 'rejected', 'refunded', 'expired')),
    payment_checkout_url         text,
    payment_provider_intent_id   uuid,
    payment_provider_status_token text,
    payment_expires_at           timestamptz,
    payment_sandbox              boolean NOT NULL DEFAULT false,
    currency                     char(3) NOT NULL,
    subtotal                     int NOT NULL CHECK (subtotal >= 0),
    total                        int NOT NULL CHECK (total >= 0),
    pickup_location              text NOT NULL,
    customer_notes               text NOT NULL DEFAULT '' CHECK (length(customer_notes) <= 1000),
    cancellation_reason          text NOT NULL DEFAULT '',
    created_at                   timestamptz NOT NULL DEFAULT now(),
    updated_at                   timestamptz NOT NULL DEFAULT now(),
    completed_at                 timestamptz,
    cancelled_at                 timestamptz
);

CREATE INDEX shop_orders_status_idx ON shop_orders (status, created_at DESC);
CREATE INDEX shop_orders_customer_idx ON shop_orders (lower(customer_email), created_at DESC);

CREATE TABLE shop_order_items (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id     uuid NOT NULL REFERENCES shop_orders(id) ON DELETE RESTRICT,
    product_id   uuid REFERENCES products(id) ON DELETE SET NULL,
    product_slug text NOT NULL,
    product_name text NOT NULL,
    sku          text NOT NULL,
    unit_price   int NOT NULL CHECK (unit_price > 0),
    quantity     int NOT NULL CHECK (quantity > 0),
    line_total   int NOT NULL CHECK (line_total > 0),
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE shop_order_status_history (
    id          bigserial PRIMARY KEY,
    order_id    uuid NOT NULL REFERENCES shop_orders(id) ON DELETE CASCADE,
    from_status text,
    to_status   text NOT NULL,
    note        text NOT NULL DEFAULT '',
    actor       text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE stock_movements (
    id         bigserial PRIMARY KEY,
    product_id uuid NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    delta      int NOT NULL CHECK (delta <> 0),
    reason     text NOT NULL DEFAULT '',
    created_by text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE payment_callback_events (
    id              bigserial PRIMARY KEY,
    provider_event_id text NOT NULL UNIQUE,
    order_id        uuid REFERENCES shop_orders(id) ON DELETE SET NULL,
    payload_hash    bytea NOT NULL CHECK (octet_length(payload_hash) = 32),
    status          text NOT NULL CHECK (status IN ('received', 'processed', 'ignored', 'failed')),
    error_code      text NOT NULL DEFAULT '',
    received_at     timestamptz NOT NULL DEFAULT now(),
    processed_at    timestamptz
);

INSERT INTO product_categories (slug, name, description, sort_order)
VALUES ('cuidado-personal', 'Cuidado personal', 'Productos profesionales para cabello y barba.', 10)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (
    category_id, sku, slug, name, description, short_description,
    price, qty, min_qty, featured, sort_order
)
SELECT c.id, seed.sku, seed.slug, seed.name, seed.description, seed.short_description,
       seed.price, seed.qty, 3, seed.featured, seed.sort_order
FROM product_categories c
CROSS JOIN (VALUES
    ('SF-CAIDA-250', 'shampoo-tratamiento-caida', 'Shampoo tratamiento para caída',
     'Shampoo masculino Sir Fausto para una rutina de cuidado del cabello.',
     'Limpieza y cuidado diario.', 21000, 18, true, 10),
    ('SF-BARBA-090', 'pomada-restauradora-barba', 'Pomada restauradora para barba',
     'Pomada Sir Fausto para acondicionar y peinar la barba.',
     'Textura y cuidado para barba.', 18500, 16, true, 20),
    ('SF-DETOX-500', 'shampoo-pure-detox', 'Shampoo Pure Detox',
     'Shampoo detoxificante Sir Fausto para limpieza profunda.',
     'Limpieza profunda de 500 ml.', 24500, 14, true, 30),
    ('SF-GROSOR-250', 'shampoo-engrosador-sin-sulfatos', 'Shampoo engrosador sin sulfatos',
     'Shampoo masculino Sir Fausto sin sulfatos para la rutina diaria.',
     'Fórmula sin sulfatos.', 22500, 18, false, 40),
    ('SF-OPACA-100', 'pomada-opaca-cabello', 'Pomada opaca para cabello',
     'Pomada Sir Fausto de acabado opaco y fijación flexible.',
     'Acabado opaco y flexible.', 19500, 20, true, 50)
) AS seed(sku, slug, name, description, short_description, price, qty, featured, sort_order)
WHERE c.slug = 'cuidado-personal'
ON CONFLICT (sku) DO NOTHING;

-- migrate:down

DROP TABLE IF EXISTS payment_callback_events;
DROP TABLE IF EXISTS stock_movements;
DROP TABLE IF EXISTS shop_order_status_history;
DROP TABLE IF EXISTS shop_order_items;
DROP TABLE IF EXISTS shop_orders;
DROP TABLE IF EXISTS shopping_cart_items;
DROP TABLE IF EXISTS shopping_carts;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS product_categories;
